---
- name: "Configure shared storage on pi"
  hosts: proxmox
  become: yes
  tasks:
    - name: "Check if exists"
      with_items: "{{ hostvars[groups['controllers'][0]]['amis'] }}"
      shell: "qm list | grep {{ item['name'] }} | awk '{print $1}'"
      register: qm_list

    - name: "Delete if exists"
      when: qm_list["results"][0]["stdout"]
      with_items: "{{ qm_list['results'] }}"
      shell: "qm destroy {{ item['stdout'] }}"
      ignore_errors: yes

    - name: "Create base image(s)"
      throttle: 1
      loop: "{{ hostvars[groups['controllers'][0]]['amis'] }}"
      shell: "qm create $(pvesh get /cluster/nextid) --memory 512 --ostype l26 --name {{ item['name'] }}-template --socket 1 --onboot no --scsi0 {{ groups['controllers'][0] }}:0,import-from=/mnt/nfs/images/{{ item['name'] }} --template"
      ignore_errors: yes
