- name: "Configure vm"
  hosts: vms
  become: true
  tasks:
    - name: "Update host controller"
      apt:
        update_cache: yes
        pkg:
          - screen
          - vim

    - name: "Get docker install script"
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: 0755
        force: true

    - name: "Install docker"
      shell: /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: "Get docker-compose"
      get_url:
        url: https://raw.githubusercontent.com/linuxserver/docker-docker-compose/v2/run.sh
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: "Add tokugero to group"
      user:
        name: tokugero
        groups: docker
        append: yes
#TODO: Come back and configure hosts dynamically for terraform to consume ansible tasks
