---
- name: Secondary Router Configuration # Note that this is assuming very first setup has occurred, ssh/ip configs/dns/etc
  hosts: router
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    ansible_user: "{{ hostvars['router']['ansible_user'] }}"
  tasks:
    - name: Deploy configuration
      vyos.vyos.vyos_interfaces:
        config:
          - name: eth0
            description: "Internal Lan 1 - Configured by Ansible"
            enabled: true
          - name: eth3
            description: "External - Configured by Ansible"
            enabled: true
        state: replaced

    - name: Set IPs
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth0 address '10.10.10.1/24'
          - set interfaces ethernet eth3 address dhcp

    - name: Setup DHCP
      vyos.vyos.vyos_config:
        lines:
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} default-router '{{ hostvars['router']['router_internal_ip'] }}'
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} name-server '{{ hostvars['router']['router_internal_ip'] }}'
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} domain-name 'minilab.tokugero.com'
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} lease '86400'
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} range 0 start '10.10.10.100'
          - set service dhcp-server shared-network-name {{ hostvars['router']['dhcp']['scope_name'] }} subnet {{ hostvars['router']['dhcp']['subnet'] }} range 0 stop '10.10.10.200'

    - name: Setup DNS
      vyos.vyos.vyos_config:
        lines:
          - set service dns forwarding cache-size 0
          - set service dns forwarding listen-address '{{ hostvars['router']['router_internal_ip'] }}'
          - set service dns forwarding allow-from '{{ hostvars['router']['dhcp']['subnet'] }}'

    - name: Setup Local DNS
      vyos.vyos.vyos_config:
        lines:
          - set system name-server 1.1.1.1

    - name: Setup NAT
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 100 outbound-interface eth3
          - set nat source rule 100 source address '{{ hostvars['router']['dhcp']['subnet'] }}'
          - set nat source rule 100 translation address masquerade

    - name: Enable SSH
      vyos.vyos.vyos_config:
        lines:
          - set service ssh port 22

    - name: Stop Docker
      command: systemctl stop docker
      vars:
        ansible_connection: ssh
        ansible_become: yes

    - name: Clear iptables
      command: iptables -F
      vars:
        ansible_connection: ssh
        ansible_become: yes

    - name: Unbind firewall rules to interfaces
      vyos.vyos.vyos_firewall_interfaces:
        config:
          - name: eth3
            access_rules:
              - afi: ipv4
                rules:
                  - name: "OUTSIDE-LOCAL"
                    direction: local
                  - name: "OUTSIDE-IN"
                    direction: in
        state: deleted

    - name: Setup firewall rules
      vyos.vyos.vyos_firewall_rules:
        config:
          - afi: ipv4
            rule_sets:
              - name: "OUTSIDE-IN"
                default_action: drop
                rules:
                  - number: 10
                    action: accept
                    state:
                      established: true
                      related: true
                    description: "Allow established sessions"
              - name: "OUTSIDE-LOCAL"
                default_action: drop
                rules:
                  - number: 10
                    action: accept
                    state:
                      established: true
                      related: true
                    description: "Allow established sessions"
                  - number: 20
                    action: accept
                    protocol: icmp
                    icmp:
                      type_name: echo-request
                    state:
                      new: true
                    description: "Allow SSH"
                  - number: 30
                    action: accept
                    protocol: tcp
                    destination:
                      port: "22"
                    state:
                      new: true
                    description: "Allow SSH"
        state: merged

    - name: Bind firewall rules to interfaces
      vyos.vyos.vyos_firewall_interfaces:
        config:
          - name: eth3
            access_rules:
              - afi: ipv4
                rules:
                  - name: "OUTSIDE-LOCAL"
                    direction: local
                  - name: "OUTSIDE-IN"
                    direction: in
        state: merged

    - name: Start Docker
      command: systemctl start docker
      vars:
        ansible_become: yes
        ansible_connection: ssh

    - name: Setup SSH keys
      vyos.vyos.vyos_config:
        lines:
          - set system login user {{ hostvars['router']['ansible_user'] }} authentication public-keys bootstrap key {{ lookup('ansible.builtin.env', 'vyos_ssh_key') }}
          - set system login user {{ hostvars['router']['ansible_user'] }} authentication public-keys bootstrap type {{ lookup('ansible.builtin.env', 'vyos_ssh_type') }}
